name: gestmob
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  google_fonts: ^0.2.0

#  firebase_core: ^0.4.0+9
#  firebase_auth: ^0.14.0+5
#  cloud_firestore: ^0.12.9+5
#  firebase_analytics: ^5.0.2

  reorderables: ^0.3.2
  draggable_container: ^0.1.8+5
  shared_preferences: ^0.5.10

  flutter_bloc: ^6.0.5
  rxdart:

  sqflite: ^1.3.0
  path_provider: ^1.6.14
  data_connection_checker: ^0.3.4
  fluttertoast: ^7.0.4
  flutter_launcher_icons: ^0.7.5

  infinite_scroll_pagination: ^1.0.0+2

  flutter_icons: ^1.1.0
  material_design_icons_flutter: 4.0.5555

  image_picker: ^0.6.7+4
  http: ^0.12.2

  flushbar: ^1.10.4
  fancy_bottom_bar: ^0.0.1

  settings_ui: ^0.4.0

  barcode_scan: any
  expandable_bottom_bar: any
  qr_flutter:
  share: ^0.6.4+3

  get_it: ^5.0.1

  local_auth: ^0.6.3+2
  vibration: ^1.5.0

  flutter_osm_plugin: ^0.3.6+4
  map_launcher: ^0.12.2

  flutter_speed_dial:
  url_launcher: ^5.7.10

  esc_pos_bluetooth:
  flutter_bluetooth_basic:
  image:

  flutter_phoenix:
  fab_circular_menu:
  floating_action_row:

  sliding_card:

  #  flutter_plugin_android_lifecycle: ^1.0.8
  #  location_permissions: ^3.0.0
  #  after_layout: ^1.0.7+2

  flutter_localizations:
    sdk: flutter

flutter_intl:
  enabled: true # Required. Must be set to true to activate the plugin. Default: false
  class_name: S # Optional. Sets the name for the generated localization class. Default: S
  main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should consist of language code and optional script and country codes separated with underscore (e.g. 'en', 'en_GB', 'zh_Hans', 'zh_Hans_CN'). Default: en


  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/article.png
    - assets/bonLivraison.png
    - assets/box.png
    - assets/BonReception.png
    - assets/commandeClient.png
    - assets/client.png
    - assets/dashboard.png
    - assets/devis.png
    - assets/factureAchat.png
    - assets/fournisseurs.png
    - assets/invoice.png
    - assets/map.png
    - assets/notification.png
    - assets/rapport.png
    - assets/setting.png
    - assets/Tresorerie.png
    - assets/addArticle.png
    - assets/logos/cirtait_logo.png
    - assets/logos/profile_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
