import 'package:gestmob/Helpers/curency/country.dart';
import 'package:gestmob/generated/l10n.dart';

List<Country> countryList = [
  Country(
    isoCode: "AF",
    currencyCode: "AFN",
    currencyName: S.current.AFN_name,
    name: "Afghanistan",
    iso3Code: "AFG",
  ),
  Country(
    isoCode: "AX",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Åland Islands",
    iso3Code: "ALA",
  ),
  Country(
    isoCode: "AL",
    currencyCode: "ALL",
    currencyName: S.current.ALL_name,
    name: "Albania",
    iso3Code: "ALB",
  ),
  Country(
    isoCode: "DZ",
    currencyCode: "DZD",
    currencyName: "${S.current.DZD_name}",
    name: "Algeria",
    iso3Code: "DZA",
  ),
  Country(
    isoCode: "AS",
    currencyCode: "USD",
    currencyName:S.current.USD_name,
    name: "American Samoa",
    iso3Code: "ASM",
  ),
  Country(
    isoCode: "AD",
    currencyCode: "EUR",
    currencyName:S.current.EUR_name,
    name: "Andorra",
    iso3Code: "AND",
  ),
  Country(
    isoCode: "AO",
    currencyCode: "AOA",
    currencyName: S.current.AOA_name,
    name: "Angola",
    iso3Code: "AGO",
  ),
  Country(
    isoCode: "AI",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Anguilla",
    iso3Code: "AIA",
  ),
  Country(
    isoCode: "AQ",
    currencyCode: "AUD",
    currencyName:S.current.AUD_name,
    name: "Antarctica",
    iso3Code: "ATA",
  ),
  Country(
    isoCode: "AG",
    currencyCode: "XCD",
    currencyName:  S.current.XCD_name,
    name: "Antigua and Barbuda",
    iso3Code: "ATG",
  ),
  Country(
    isoCode: "AR",
    currencyCode: "ARS",
    currencyName: S.current.ARS_name,
    name: "Argentina",
    iso3Code: "ARG",
  ),
  Country(
    isoCode: "AM",
    currencyCode: "AMD",
    currencyName: S.current.AMD_name,
    name: "Armenia",
    iso3Code: "ARM",
  ),
  Country(
    isoCode: "AW",
    currencyCode: "AWG",
    currencyName: S.current.AWG_name,
    name: "Aruba",
    iso3Code: "ABW",
  ),
  Country(
    isoCode: "AU",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Australia",
    iso3Code: "AUS",
  ),
  Country(
    isoCode: "AT",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Austria",
    iso3Code: "AUT",
  ),
  Country(
    isoCode: "AZ",
    currencyCode: "AZN",
    currencyName: S.current.AZN_name,
    name: "Azerbaijan",
    iso3Code: "AZE",
  ),
  Country(
    isoCode: "BS",
    currencyCode: "BSD",
    currencyName: S.current.BSD_name,
    name: "Bahamas",
    iso3Code: "BHS",
  ),
  Country(
    isoCode: "BH",
    currencyCode: "BHD",
    currencyName: S.current.BHD_name,
    name: "Bahrain",
    iso3Code: "BHR",
  ),
  Country(
    isoCode: "BD",
    currencyCode: "BDT",
    currencyName:  S.current.BDT_name,
    name: "Bangladesh",
    iso3Code: "BGD",
  ),
  Country(
    isoCode: "BB",
    currencyCode: "BBD",
    currencyName: S.current.BBD_name,
    name: "Barbados",
    iso3Code: "BRB",
  ),
  Country(
    isoCode: "BY",
    currencyCode: "BYN",
    currencyName: S.current.BYN_name,
    name: "Belarus",
    iso3Code: "BLR",
  ),
  Country(
    isoCode: "BE",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Belgium",
    iso3Code: "BEL",
  ),
  Country(
    isoCode: "BZ",
    currencyCode: "BZD",
    currencyName: S.current.BZD_name,
    name: "Belize",
    iso3Code: "BLZ",
  ),
  Country(
    isoCode: "BJ",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Benin",
    iso3Code: "BEN",
  ),
  Country(
    isoCode: "BM",
    currencyCode: "BMD",
    currencyName: S.current.BMD_name,
    name: "Bermuda",
    iso3Code: "BMU",
  ),
  Country(
    isoCode: "BT",
    currencyCode: "BTN",
    currencyName:  S.current.BTN_name,
    name: "Bhutan",
    iso3Code: "BTN",
  ),
  Country(
    isoCode: "BO",
    currencyCode: "BOB",
    currencyName: S.current.BOB_name,
    name: "Bolivia (Plurinational State of)",
    iso3Code: "BOL",
  ),
  Country(
    isoCode: "BQ",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Bonaire, Sint Eustatius and Saba",
    iso3Code: "BES",
  ),
  Country(
    isoCode: "BA",
    currencyCode: "BAM",
    currencyName: S.current.BAM_name,
    name: "Bosnia and Herzegovina",
    iso3Code: "BIH",
  ),
  Country(
    isoCode: "BW",
    currencyCode: "BWP",
    currencyName: S.current.BWP_name,
    name: "Botswana",
    iso3Code: "BWA",
  ),
  Country(
    isoCode: "BV",
    currencyCode: "NOK",
    currencyName: S.current.NOK_name,
    name: "Bouvet Island",
    iso3Code: "BVT",
  ),
  Country(
    isoCode: "BR",
    currencyCode: "BRL",
    currencyName: S.current.BRL_name,
    name: "Brazil",
    iso3Code: "BRA",
  ),
  Country(
    isoCode: "IO",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "British Indian Ocean Territory",
    iso3Code: "IOT",
  ),
  Country(
    isoCode: "VG",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Virgin Islands (British)",
    iso3Code: "VGB",
  ),
  Country(
    isoCode: "VI",
    currencyCode: "USD",
    currencyName:  S.current.USD_name,
    name: "Virgin Islands (U.S.)",
    iso3Code: "VIR",
  ),
  Country(
    isoCode: "BN",
    currencyCode: "BND",
    currencyName: S.current.BND_name,
    name: "Brunei Darussalam",
    iso3Code: "BRN",
  ),
  Country(
    isoCode: "BG",
    currencyCode: "BGN",
    currencyName: S.current.BGN_name,
    name: "Bulgaria",
    iso3Code: "BGR",
  ),
  Country(
    isoCode: "BF",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Burkina Faso",
    iso3Code: "BFA",
  ),
  Country(
    isoCode: "BI",
    currencyCode: "BIF",
    currencyName: S.current.BIF_name,
    name: "Burundi",
    iso3Code: "BDI",
  ),
  Country(
    isoCode: "KH",
    currencyCode: "KHR",
    currencyName: S.current.KHR_name,
    name: "Cambodia",
    iso3Code: "KHM",
  ),
  Country(
    isoCode: "CM",
    currencyCode: "XAF",
    currencyName: S.current.XAF_name,
    name: "Cameroon",
    iso3Code: "CMR",
  ),
  Country(
    isoCode: "CA",
    currencyCode: "CAD",
    currencyName: S.current.CAD_name,
    name: "Canada",
    iso3Code: "CAN",
  ),
  Country(
    isoCode: "CV",
    currencyCode: "CVE",
    currencyName:S.current.CVE_name,
    name: "Cabo Verde",
    iso3Code: "CPV",
  ),
  Country(
    isoCode: "KY",
    currencyCode: "KYD",
    currencyName: S.current.KYD_name,
    name: "Cayman Islands",
    iso3Code: "CYM",
  ),
  Country(
    isoCode: "CF",
    currencyCode: "XAF",
    currencyName: S.current.XAF_name,
    name: "Central African Republic",
    iso3Code: "CAF",
  ),
  Country(
    isoCode: "TD",
    currencyCode: "XAF",
    currencyName: S.current.XAF_name,
    name: "Chad",
    iso3Code: "TCD",
  ),
  Country(
    isoCode: "CL",
    currencyCode: "CLP",
    currencyName:S.current.CLP_name,
    name: "Chile",
    iso3Code: "CHL",
  ),
  Country(
    isoCode: "CN",
    currencyCode: "CNY",
    currencyName: S.current.CNY_name,
    name: "China",
    iso3Code: "CHN",
  ),
  Country(
    isoCode: "CX",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Christmas Island",
    iso3Code: "CXR",
  ),
  Country(
    isoCode: "CC",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Cocos (Keeling) Islands",
    iso3Code: "CCK",
  ),
  Country(
    isoCode: "CO",
    currencyCode: "COP",
    currencyName:  S.current.COP_name,
    name: "Colombia",
    iso3Code: "COL",
  ),
  Country(
    isoCode: "KM",
    currencyCode: "KMF",
    currencyName: S.current.KMF_name,
    name: "Comoros",
    iso3Code: "COM",
  ),
  Country(
    isoCode: "CG",
    currencyCode: "XAF",
    currencyName: S.current.XAF_name,
    name: "Congo",
    iso3Code: "COG",
  ),
  Country(
    isoCode: "CD",
    currencyCode: "CDF",
    currencyName:S.current.CDF_name,
    name: "Congo (Democratic Republic of the)",
    iso3Code: "COD",
  ),
  Country(
    isoCode: "CK",
    currencyCode: "NZD",
    currencyName: S.current.NZD_name,
    name: "Cook Islands",
    iso3Code: "COK",
  ),
  Country(
    isoCode: "CR",
    currencyCode: "CRC",
    currencyName:S.current.CRC_name,
    name: "Costa Rica",
    iso3Code: "CRI",
  ),
  Country(
    isoCode: "HR",
    currencyCode: "HRK",
    currencyName: S.current.HRK_name,
    name: "Croatia",
    iso3Code: "HRV",
  ),
  Country(
    isoCode: "CU",
    currencyCode: "CUC",
    currencyName: S.current.CUC_name,
    name: "Cuba",
    iso3Code: "CUB",
  ),
  Country(
    isoCode: "CW",
    currencyCode: "ANG",
    currencyName: S.current.ANG_name,
    name: "Curaçao",
    iso3Code: "CUW",
  ),
  Country(
    isoCode: "CY",
    currencyCode: "EUR",
    currencyName:S.current.EUR_name,
    name: "Cyprus",
    iso3Code: "CYP",
  ),
  Country(
    isoCode: "CZ",
    currencyCode: "CZK",
    currencyName: S.current.CZK_name,
    name: "Czech Republic",
    iso3Code: "CZE",
  ),
  Country(
    isoCode: "DK",
    currencyCode: "DKK",
    currencyName: S.current.DKK_name,
    name: "Denmark",
    iso3Code: "DNK",
  ),
  Country(
    isoCode: "DJ",
    currencyCode: "DJF",
    currencyName: S.current.DJF_name,
    name: "Djibouti",
    iso3Code: "DJI",
  ),
  Country(
    isoCode: "DM",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Dominica",
    iso3Code: "DMA",
  ),
  Country(
    isoCode: "DO",
    currencyCode: "DOP",
    currencyName: S.current.DOP_name,
    name: "Dominican Republic",
    iso3Code: "DOM",
  ),
  Country(
    isoCode: "EC",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Ecuador",
    iso3Code: "ECU",
  ),
  Country(
    isoCode: "EG",
    currencyCode: "EGP",
    currencyName:  S.current.EGP_name,
    name: "Egypt",
    iso3Code: "EGY",
  ),
  Country(
    isoCode: "SV",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "El Salvador",
    iso3Code: "SLV",
  ),
  Country(
    isoCode: "GQ",
    currencyCode: "XAF",
    currencyName: S.current.XAF_name,
    name: "Equatorial Guinea",
    iso3Code: "GNQ",
  ),
  Country(
    isoCode: "ER",
    currencyCode: "ERN",
    currencyName: S.current.ERN_name,
    name: "Eritrea",
    iso3Code: "ERI",
  ),
  Country(
    isoCode: "EE",
    currencyCode: "EUR",
    currencyName:  S.current.EUR_name,
    name: "Estonia",
    iso3Code: "EST",
  ),
  Country(
    isoCode: "ET",
    currencyCode: "ETB",
    currencyName: S.current.ETB_name,
    name: "Ethiopia",
    iso3Code: "ETH",
  ),
  Country(
    isoCode: "FK",
    currencyCode: "FKP",
    currencyName: S.current.FKP_name,
    name: "Falkland Islands (Malvinas)",
    iso3Code: "FLK",
  ),
  Country(
    isoCode: "FO",
    currencyCode: "DKK",
    currencyName: S.current.DKK_name,
    name: "Faroe Islands",
    iso3Code: "FRO",
  ),
  Country(
    isoCode: "FJ",
    currencyCode: "FJD",
    currencyName: S.current.FJD_name,
    name: "Fiji",
    iso3Code: "FJI",
  ),
  Country(
    isoCode: "FI",
    currencyCode: "EUR",
    currencyName:S.current.EUR_name,
    name: "Finland",
    iso3Code: "FIN",
  ),
  Country(
    isoCode: "FR",
    currencyCode: "EUR",
    currencyName:  S.current.EUR_name,
    name: "France",
    iso3Code: "FRA",
  ),
  Country(
    isoCode: "GF",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "French Guiana",
    iso3Code: "GUF",
  ),
  Country(
    isoCode: "PF",
    currencyCode: "XPF",
    currencyName:  S.current.XPF_name,
    name: "French Polynesia",
    iso3Code: "PYF",
  ),
  Country(
    isoCode: "TF",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "French Southern Territories",
    iso3Code: "ATF",
  ),
  Country(
    isoCode: "GA",
    currencyCode: "XAF",
    currencyName:S.current.XAF_name,
    name: "Gabon",
    iso3Code: "GAB",
  ),
  Country(
    isoCode: "GM",
    currencyCode: "GMD",
    currencyName:S.current.GMD_name,
    name: "Gambia",
    iso3Code: "GMB",
  ),
  Country(
    isoCode: "GE",
    currencyCode: "GEL",
    currencyName: S.current.GEL_name,
    name: "Georgia",
    iso3Code: "GEO",
  ),
  Country(
    isoCode: "DE",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Germany",
    iso3Code: "DEU",
  ),
  Country(
    isoCode: "GH",
    currencyCode: "GHS",
    currencyName:S.current.GHS_name,
    name: "Ghana",
    iso3Code: "GHA",
  ),
  Country(
    isoCode: "GI",
    currencyCode: "GIP",
    currencyName:S.current.GIP_name,
    name: "Gibraltar",
    iso3Code: "GIB",
  ),
  Country(
    isoCode: "GR",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Greece",
    iso3Code: "GRC",
  ),
  Country(
    isoCode: "GL",
    currencyCode: "DKK",
    currencyName: S.current.DKK_name,
    name: "Greenland",
    iso3Code: "GRL",
  ),
  Country(
    isoCode: "GD",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Grenada",
    iso3Code: "GRD",
  ),
  Country(
    isoCode: "GP",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Guadeloupe",
    iso3Code: "GLP",
  ),
  Country(
    isoCode: "GU",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Guam",
    iso3Code: "GUM",
  ),
  Country(
    isoCode: "GT",
    currencyCode: "GTQ",
    currencyName: S.current.GTQ_name,
    name: "Guatemala",
    iso3Code: "GTM",
  ),
  Country(
    isoCode: "GG",
    currencyCode: "GBP",
    currencyName: S.current.GBP_name,
    name: "Guernsey",
    iso3Code: "GGY",
  ),
  Country(
    isoCode: "GN",
    currencyCode: "GNF",
    currencyName: S.current.GNF_name,
    name: "Guinea",
    iso3Code: "GIN",
  ),
  Country(
    isoCode: "GW",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Guinea-Bissau",
    iso3Code: "GNB",
  ),
  Country(
    isoCode: "GY",
    currencyCode: "GYD",
    currencyName: S.current.GYD_name,
    name: "Guyana",
    iso3Code: "GUY",
  ),
  Country(
    isoCode: "HT",
    currencyCode: "HTG",
    currencyName: S.current.HTG_name,
    name: "Haiti",
    iso3Code: "HTI",
  ),
  Country(
    isoCode: "HM",
    currencyCode: "AUD",
    currencyName: S.current.EUR_name,
    name: "Heard Island and McDonald Islands",
    iso3Code: "HMD",
  ),
  Country(
    isoCode: "VA",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Holy See",
    iso3Code: "VAT",
  ),
  Country(
    isoCode: "HN",
    currencyCode: "HNL",
    currencyName: S.current.HNL_name,
    name: "Honduras",
    iso3Code: "HND",
  ),
  Country(
    isoCode: "HK",
    currencyCode: "HKD",
    currencyName: S.current.HKD_name,
    name: "Hong Kong",
    iso3Code: "HKG",
  ),
  Country(
    isoCode: "HU",
    currencyCode: "HUF",
    currencyName: S.current.HUF_name,
    name: "Hungary",
    iso3Code: "HUN",
  ),
  Country(
    isoCode: "IS",
    currencyCode: "ISK",
    currencyName: S.current.ISK_name,
    name: "Iceland",
    iso3Code: "ISL",
  ),
  Country(
    isoCode: "IN",
    currencyCode: "INR",
    currencyName:  S.current.INR_name,
    name: "India",
    iso3Code: "IND",
  ),
  Country(
    isoCode: "ID",
    currencyCode: "IDR",
    currencyName: S.current.IDR_name,
    name: "Indonesia",
    iso3Code: "IDN",
  ),
  Country(
    isoCode: "CI",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Côte d'Ivoire",
    iso3Code: "CIV",
  ),
  Country(
    isoCode: "IR",
    currencyCode: "IRR",
    currencyName:  S.current.IRR_name,
    name: "Iran (Islamic Republic of)",
    iso3Code: "IRN",
  ),
  Country(
    isoCode: "IQ",
    currencyCode: "IQD",
    currencyName: S.current.IQD_name,
    name: "Iraq",
    iso3Code: "IRQ",
  ),
  Country(
    isoCode: "IE",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Ireland",
    iso3Code: "IRL",
  ),
  Country(
    isoCode: "IM",
    currencyCode: "GBP",
    currencyName: S.current.GBP_name,
    name: "Isle of Man",
    iso3Code: "IMN",
  ),
  Country(
    isoCode: "IT",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Italy",
    iso3Code: "ITA",
  ),
  Country(
    isoCode: "JM",
    currencyCode: "JMD",
    currencyName: S.current.JMD_name,
    name: "Jamaica",
    iso3Code: "JAM",
  ),
  Country(
    isoCode: "JP",
    currencyCode: "JPY",
    currencyName: S.current.JPY_name,
    name: "Japan",
    iso3Code: "JPN",
  ),
  Country(
    isoCode: "JE",
    currencyCode: "GBP",
    currencyName: S.current.GBP_name,
    name: "Jersey",
    iso3Code: "JEY",
  ),
  Country(
    isoCode: "JO",
    currencyCode: "JOD",
    currencyName: S.current.JOD_name,
    name: "Jordan",
    iso3Code: "JOR",
  ),
  Country(
    isoCode: "KZ",
    currencyCode: "KZT",
    currencyName:  S.current.KZT_name,
    name: "Kazakhstan",
    iso3Code: "KAZ",
  ),
  Country(
    isoCode: "KE",
    currencyCode: "KES",
    currencyName: S.current.KES_name,
    name: "Kenya",
    iso3Code: "KEN",
  ),
  Country(
    isoCode: "KI",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Kiribati",
    iso3Code: "KIR",
  ),
  Country(
    isoCode: "KW",
    currencyCode: "KWD",
    currencyName:  S.current.KWD_name,
    name: "Kuwait",
    iso3Code: "KWT",
  ),
  Country(
    isoCode: "KG",
    currencyCode: "KGS",
    currencyName: S.current.KGS_name,
    name: "Kyrgyzstan",
    iso3Code: "KGZ",
  ),
  Country(
    isoCode: "LA",
    currencyCode: "LAK",
    currencyName: S.current.LAK_name,
    name: "Lao People's Democratic Republic",
    iso3Code: "LAO",
  ),
  Country(
    isoCode: "LV",
    currencyCode: "EUR",
    currencyName:S.current.EUR_name,
    name: "Latvia",
    iso3Code: "LVA",
  ),
  Country(
    isoCode: "LB",
    currencyCode: "LBP",
    currencyName: S.current.LBP_name,
    name: "Lebanon",
    iso3Code: "LBN",
  ),
  Country(
    isoCode: "LS",
    currencyCode: "LSL",
    currencyName:  S.current.LSL_name,
    name: "Lesotho",
    iso3Code: "LSO",
  ),
  Country(
    isoCode: "LR",
    currencyCode: "LRD",
    currencyName: S.current.LRD_name,
    name: "Liberia",
    iso3Code: "LBR",
  ),
  Country(
    isoCode: "LY",
    currencyCode: "LYD",
    currencyName:  S.current.LYD_name,
    name: "Libya",
    iso3Code: "LBY",
  ),
  Country(
    isoCode: "LI",
    currencyCode: "CHF",
    currencyName: S.current.CHF_name,
    name: "Liechtenstein",
    iso3Code: "LIE",
  ),
  Country(
    isoCode: "LT",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Lithuania",
    iso3Code: "LTU",
  ),
  Country(
    isoCode: "LU",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Luxembourg",
    iso3Code: "LUX",
  ),
  Country(
    isoCode: "MO",
    currencyCode: "MOP",
    currencyName: S.current.MOP_name,
    name: "Macao",
    iso3Code: "MAC",
  ),
  Country(
    isoCode: "MK",
    currencyCode: "MKD",
    currencyName: S.current.MKD_name,
    name: "Macedonia (the former Yugoslav Republic of)",
    iso3Code: "MKD",
  ),
  Country(
    isoCode: "MG",
    currencyCode: "MGA",
    currencyName: S.current.MGA_name,
    name: "Madagascar",
    iso3Code: "MDG",
  ),
  Country(
    isoCode: "MW",
    currencyCode: "MWK",
    currencyName: S.current.MWK_name,
    name: "Malawi",
    iso3Code: "MWI",
  ),
  Country(
    isoCode: "MY",
    currencyCode: "MYR",
    currencyName: S.current.MYR_name,
    name: "Malaysia",
    iso3Code: "MYS",
  ),
  Country(
    isoCode: "MV",
    currencyCode: "MVR",
    currencyName: S.current.MVR_name,
    name: "Maldives",
    iso3Code: "MDV",
  ),
  Country(
    isoCode: "ML",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Mali",
    iso3Code: "MLI",
  ),
  Country(
    isoCode: "MT",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Malta",
    iso3Code: "MLT",
  ),
  Country(
    isoCode: "MH",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Marshall Islands",
    iso3Code: "MHL",
  ),
  Country(
    isoCode: "MQ",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Martinique",
    iso3Code: "MTQ",
  ),
  Country(
    isoCode: "MR",
    currencyCode: "MRO",
    currencyName:  S.current.MRO_name,
    name: "Mauritania",
    iso3Code: "MRT",
  ),
  Country(
    isoCode: "MU",
    currencyCode: "MUR",
    currencyName: S.current.MUR_name,
    name: "Mauritius",
    iso3Code: "MUS",
  ),
  Country(
    isoCode: "YT",
    currencyCode: "EUR",
    currencyName:  S.current.EUR_name,
    name: "Mayotte",
    iso3Code: "MYT",
  ),
  Country(
    isoCode: "MX",
    currencyCode: "MXN",
    currencyName: S.current.MXN_name,
    name: "Mexico",
    iso3Code: "MEX",
  ),
  Country(
    isoCode: "FM",
    currencyCode: "None",
    currencyName: S.current.None_name,
    name: "Micronesia (Federated States of)",
    iso3Code: "FSM",
  ),
  Country(
    isoCode: "MD",
    currencyCode: "MDL",
    currencyName: S.current.MDL_name,
    name: "Moldova (Republic of)",
    iso3Code: "MDA",
  ),
  Country(
    isoCode: "MC",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Monaco",
    iso3Code: "MCO",
  ),
  Country(
    isoCode: "MN",
    currencyCode: "MNT",
    currencyName: S.current.MNT_name,
    name: "Mongolia",
    iso3Code: "MNG",
  ),
  Country(
    isoCode: "ME",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Montenegro",
    iso3Code: "MNE",
  ),
  Country(
    isoCode: "MS",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Montserrat",
    iso3Code: "MSR",
  ),
  Country(
    isoCode: "MA",
    currencyCode: "MAD",
    currencyName: S.current.MAD_name,
    name: "Morocco",
    iso3Code: "MAR",
  ),
  Country(
    isoCode: "MZ",
    currencyCode: "MZN",
    currencyName:S.current.MZN_name,
    name: "Mozambique",
    iso3Code: "MOZ",
  ),
  Country(
    isoCode: "MM",
    currencyCode: "MMK",
    currencyName:  S.current.MMK_name,
    name: "Myanmar",
    iso3Code: "MMR",
  ),
  Country(
    isoCode: "NA",
    currencyCode: "NAD",
    currencyName: S.current.NAD_name,
    name: "Namibia",
    iso3Code: "NAM",
  ),
  Country(
    isoCode: "NR",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Nauru",
    iso3Code: "NRU",
  ),
  Country(
    isoCode: "NP",
    currencyCode: "NPR",
    currencyName: S.current.NPR_name,
    name: "Nepal",
    iso3Code: "NPL",
  ),
  Country(
    isoCode: "NL",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Netherlands",
    iso3Code: "NLD",
  ),
  Country(
    isoCode: "NC",
    currencyCode: "XPF",
    currencyName: S.current.XPF_name,
    name: "New Caledonia",
    iso3Code: "NCL",
  ),
  Country(
    isoCode: "NZ",
    currencyCode: "NZD",
    currencyName:  S.current.NZD_name,
    name: "New Zealand",
    iso3Code: "NZL",
  ),
  Country(
    isoCode: "NI",
    currencyCode: "NIO",
    currencyName:  S.current.NIO_name,
    name: "Nicaragua",
    iso3Code: "NIC",
  ),
  Country(
    isoCode: "NE",
    currencyCode: "XOF",
    currencyName:  S.current.XOF_name,
    name: "Niger",
    iso3Code: "NER",
  ),
  Country(
    isoCode: "NG",
    currencyCode: "NGN",
    currencyName: S.current.NGN_name,
    name: "Nigeria",
    iso3Code: "NGA",
  ),
  Country(
    isoCode: "NU",
    currencyCode: "NZD",
    currencyName: S.current.NZD_name,
    name: "Niue",
    iso3Code: "NIU",
  ),
  Country(
    isoCode: "NF",
    currencyCode: "AUD",
    currencyName:  S.current.AUD_name,
    name: "Norfolk Island",
    iso3Code: "NFK",
  ),
  Country(
    isoCode: "KP",
    currencyCode: "KPW",
    currencyName: S.current.KPW_name,
    name: "Korea (Democratic People's Republic of)",
    iso3Code: "PRK",
  ),
  Country(
    isoCode: "MP",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Northern Mariana Islands",
    iso3Code: "MNP",
  ),
  Country(
    isoCode: "NO",
    currencyCode: "NOK",
    currencyName: S.current.NOK_name,
    name: "Norway",
    iso3Code: "NOR",
  ),
  Country(
    isoCode: "OM",
    currencyCode: "OMR",
    currencyName: S.current.OMR_name,
    name: "Oman",
    iso3Code: "OMN",
  ),
  Country(
    isoCode: "PK",
    currencyCode: "PKR",
    currencyName: S.current.PKR_name,
    name: "Pakistan",
    iso3Code: "PAK",
  ),
  Country(
    isoCode: "PW",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Palau",
    iso3Code: "PLW",
  ),
  Country(
    isoCode: "PS",
    currencyCode: "ILS",
    currencyName:  S.current.ILS_name,
    name: "Palestine, State of",
    iso3Code: "PSE",
  ),
  Country(
    isoCode: "PA",
    currencyCode: "PAB",
    currencyName:  S.current.PAB_name,
    name: "Panama",
    iso3Code: "PAN",
  ),
  Country(
    isoCode: "PG",
    currencyCode: "PGK",
    currencyName: S.current.PGK_name,
    name: "Papua New Guinea",
    iso3Code: "PNG",
  ),
  Country(
    isoCode: "PY",
    currencyCode: "PYG",
    currencyName: S.current.PYG_name,
    name: "Paraguay",
    iso3Code: "PRY",
  ),
  Country(
    isoCode: "PE",
    currencyCode: "PEN",
    currencyName:S.current.PEN_name,
    name: "Peru",
    iso3Code: "PER",
  ),
  Country(
    isoCode: "PH",
    currencyCode: "PHP",
    currencyName: S.current.PHP_name,
    name: "Philippines",
    iso3Code: "PHL",
  ),
  Country(
    isoCode: "PN",
    currencyCode: "NZD",
    currencyName: S.current.NZD_name,
    name: "Pitcairn",
    iso3Code: "PCN",
  ),
  Country(
    isoCode: "PL",
    currencyCode: "PLN",
    currencyName: S.current.PLN_name,
    name: "Poland",
    iso3Code: "POL",
  ),
  Country(
    isoCode: "PT",
    currencyCode: "EUR",
    currencyName:  S.current.EUR_name,
    name: "Portugal",
    iso3Code: "PRT",
  ),
  Country(
    isoCode: "PR",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Puerto Rico",
    iso3Code: "PRI",
  ),
  Country(
    isoCode: "QA",
    currencyCode: "QAR",
    currencyName: S.current.QAR_name,
    name: "Qatar",
    iso3Code: "QAT",
  ),
  Country(
    isoCode: "XK",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Republic of Kosovo",
    iso3Code: "KOS",
  ),
  Country(
    isoCode: "RE",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Réunion",
    iso3Code: "REU",
  ),
  Country(
    isoCode: "RO",
    currencyCode: "RON",
    currencyName: S.current.RON_name,
    name: "Romania",
    iso3Code: "ROU",
  ),
  Country(
    isoCode: "RU",
    currencyCode: "RUB",
    currencyName: S.current.RUB_name,
    name: "Russian Federation",
    iso3Code: "RUS",
  ),
  Country(
    isoCode: "RW",
    currencyCode: "RWF",
    currencyName: S.current.RWF_name,
    name: "Rwanda",
    iso3Code: "RWA",
  ),
  Country(
    isoCode: "BL",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Saint Barthélemy",
    iso3Code: "BLM",
  ),
  Country(
    isoCode: "SH",
    currencyCode: "SHP",
    currencyName: S.current.SHP_name,
    name: "Saint Helena, Ascension and Tristan da Cunha",
    iso3Code: "SHN",
  ),
  Country(
    isoCode: "KN",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Saint Kitts and Nevis",
    iso3Code: "KNA",
  ),
  Country(
    isoCode: "LC",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Saint Lucia",
    iso3Code: "LCA",
  ),
  Country(
    isoCode: "MF",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Saint Martin (French part)",
    iso3Code: "MAF",
  ),
  Country(
    isoCode: "PM",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Saint Pierre and Miquelon",
    iso3Code: "SPM",
  ),
  Country(
    isoCode: "VC",
    currencyCode: "XCD",
    currencyName: S.current.XCD_name,
    name: "Saint Vincent and the Grenadines",
    iso3Code: "VCT",
  ),
  Country(
    isoCode: "WS",
    currencyCode: "WST",
    currencyName: S.current.WST_name,
    name: "Samoa",
    iso3Code: "WSM",
  ),
  Country(
    isoCode: "SM",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "San Marino",
    iso3Code: "SMR",
  ),
  Country(
    isoCode: "ST",
    currencyCode: "STD",
    currencyName: S.current.STD_name,
    name: "Sao Tome and Principe",
    iso3Code: "STP",
  ),
  Country(
    isoCode: "SA",
    currencyCode: "SAR",
    currencyName: S.current.SAR_name,
    name: "Saudi Arabia",
    iso3Code: "SAU",
  ),
  Country(
    isoCode: "SN",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Senegal",
    iso3Code: "SEN",
  ),
  Country(
    isoCode: "RS",
    currencyCode: "RSD",
    currencyName:  S.current.RSD_name,
    name: "Serbia",
    iso3Code: "SRB",
  ),
  Country(
    isoCode: "SC",
    currencyCode: "SCR",
    currencyName: S.current.SCR_name,
    name: "Seychelles",
    iso3Code: "SYC",
  ),
  Country(
    isoCode: "SL",
    currencyCode: "SLL",
    currencyName: S.current.SLL_name,
    name: "Sierra Leone",
    iso3Code: "SLE",
  ),
  Country(
    isoCode: "SG",
    currencyCode: "SGD",
    currencyName:  S.current.SGD_name,
    name: "Singapore",
    iso3Code: "SGP",
  ),
  Country(
    isoCode: "SX",
    currencyCode: "ANG",
    currencyName: S.current.ANG_name,
    name: "Sint Maarten (Dutch part)",
    iso3Code: "SXM",
  ),
  Country(
    isoCode: "SK",
    currencyCode: "EUR",
    currencyName:S.current.EUR_name,
    name: "Slovakia",
    iso3Code: "SVK",
  ),
  Country(
    isoCode: "SI",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Slovenia",
    iso3Code: "SVN",
  ),
  Country(
    isoCode: "SB",
    currencyCode: "SBD",
    currencyName: S.current.SBD_name,
    name: "Solomon Islands",
    iso3Code: "SLB",
  ),
  Country(
    isoCode: "SO",
    currencyCode: "SOS",
    currencyName: S.current.SOS_name,
    name: "Somalia",
    iso3Code: "SOM",
  ),
  Country(
    isoCode: "ZA",
    currencyCode: "ZAR",
    currencyName: S.current.ZAR_name,
    name: "South Africa",
    iso3Code: "ZAF",
  ),
  Country(
    isoCode: "GS",
    currencyCode: "GBP",
    currencyName:  S.current.GBP_name,
    name: "South Georgia and the South Sandwich Islands",
    iso3Code: "SGS",
  ),
  Country(
    isoCode: "KR",
    currencyCode: "KRW",
    currencyName: S.current.KRW_name,
    name: "Korea (Republic of)",
    iso3Code: "KOR",
  ),
  Country(
    isoCode: "SS",
    currencyCode: "SSP",
    currencyName:  S.current.SSP_name,
    name: "South Sudan",
    iso3Code: "SSD",
  ),
  Country(
    isoCode: "ES",
    currencyCode: "EUR",
    currencyName: S.current.EUR_name,
    name: "Spain",
    iso3Code: "ESP",
  ),
  Country(
    isoCode: "LK",
    currencyCode: "LKR",
    currencyName: S.current.LKR_name,
    name: "Sri Lanka",
    iso3Code: "LKA",
  ),
  Country(
    isoCode: "SD",
    currencyCode: "SDG",
    currencyName: S.current.SDG_name,
    name: "Sudan",
    iso3Code: "SDN",
  ),
  Country(
    isoCode: "SR",
    currencyCode: "SRD",
    currencyName:  S.current.SRD_name,
    name: "Suriname",
    iso3Code: "SUR",
  ),
  Country(
    isoCode: "SJ",
    currencyCode: "NOK",
    currencyName: S.current.NOK_name,
    name: "Svalbard and Jan Mayen",
    iso3Code: "SJM",
  ),
  Country(
    isoCode: "SZ",
    currencyCode: "SZL",
    currencyName: S.current.SZL_name,
    name: "Swaziland",
    iso3Code: "SWZ",
  ),
  Country(
    isoCode: "SE",
    currencyCode: "SEK",
    currencyName: S.current.SEK_name,
    name: "Sweden",
    iso3Code: "SWE",
  ),
  Country(
    isoCode: "CH",
    currencyCode: "CHF",
    currencyName: S.current.CHF_name,
    name: "Switzerland",
    iso3Code: "CHE",
  ),
  Country(
    isoCode: "SY",
    currencyCode: "SYP",
    currencyName: S.current.SYP_name,
    name: "Syrian Arab Republic",
    iso3Code: "SYR",
  ),
  Country(
    isoCode: "TW",
    currencyCode: "TWD",
    currencyName:  S.current.TWD_name,
    name: "Taiwan",
    iso3Code: "TWN",
  ),
  Country(
    isoCode: "TJ",
    currencyCode: "TJS",
    currencyName: S.current.TJS_name,
    name: "Tajikistan",
    iso3Code: "TJK",
  ),
  Country(
    isoCode: "TZ",
    currencyCode: "TZS",
    currencyName:  S.current.TZS_name,
    name: "Tanzania, United Republic of",
    iso3Code: "TZA",
  ),
  Country(
    isoCode: "TH",
    currencyCode: "THB",
    currencyName: S.current.THB_name,
    name: "Thailand",
    iso3Code: "THA",
  ),
  Country(
    isoCode: "TL",
    currencyCode: "USD",
    currencyName: S.current.USD_name,
    name: "Timor-Leste",
    iso3Code: "TLS",
  ),
  Country(
    isoCode: "TG",
    currencyCode: "XOF",
    currencyName: S.current.XOF_name,
    name: "Togo",
    iso3Code: "TGO",
  ),
  Country(
    isoCode: "TK",
    currencyCode: "NZD",
    currencyName: S.current.NZD_name,
    name: "Tokelau",
    iso3Code: "TKL",
  ),
  Country(
    isoCode: "TO",
    currencyCode: "TOP",
    currencyName: S.current.TOP_name,
    name: "Tonga",
    iso3Code: "TON",
  ),
  Country(
    isoCode: "TT",
    currencyCode: "TTD",
    currencyName: S.current.TTD_name,
    name: "Trinidad and Tobago",
    iso3Code: "TTO",
  ),
  Country(
    isoCode: "TN",
    currencyCode: "TND",
    currencyName:   S.current.TND_name,
    name: "Tunisia",
    iso3Code: "TUN",
  ),
  Country(
    isoCode: "TR",
    currencyCode: "TRY",
    currencyName:  S.current.TRY_name,
    name: "Turkey",
    iso3Code: "TUR",
  ),
  Country(
    isoCode: "TM",
    currencyCode: "TMT",
    currencyName:  S.current.TMT_name,
    name: "Turkmenistan",
    iso3Code: "TKM",
  ),
  Country(
    isoCode: "TC",
    currencyCode: "USD",
    currencyName:  S.current.USD_name,
    name: "Turks and Caicos Islands",
    iso3Code: "TCA",
  ),
  Country(
    isoCode: "TV",
    currencyCode: "AUD",
    currencyName: S.current.AUD_name,
    name: "Tuvalu",
    iso3Code: "TUV",
  ),
  Country(
    isoCode: "UG",
    currencyCode: "UGX",
    currencyName: S.current.UGX_name,
    name: "Uganda",
    iso3Code: "UGA",
  ),
  Country(
    isoCode: "UA",
    currencyCode: "UAH",
    currencyName: S.current.UAH_name,
    name: "Ukraine",
    iso3Code: "UKR",
  ),
  Country(
    isoCode: "AE",
    currencyCode: "AED",
    currencyName: S.current.AED_name,
    name: "United Arab Emirates",
    iso3Code: "ARE",
  ),
  Country(
    isoCode: "GB",
    currencyCode: "GBP",
    currencyName: S.current.GBP_name,
    name: "United Kingdom of Great Britain and Northern Ireland",
    iso3Code: "GBR",
  ),
  Country(
    isoCode: "US",
    currencyCode: "USD",
    currencyName:  S.current.USD_name,
    name: "United States of America",
    iso3Code: "USA",
  ),
  Country(
    isoCode: "UY",
    currencyCode: "UYU",
    currencyName:  S.current.UYU_name,
    name: "Uruguay",
    iso3Code: "URY",
  ),
  Country(
    isoCode: "UZ",
    currencyCode: "UZS",
    currencyName: S.current.UZS_name,
    name: "Uzbekistan",
    iso3Code: "UZB",
  ),
  Country(
    isoCode: "VU",
    currencyCode: "VUV",
    currencyName: S.current.VUV_name,
    name: "Vanuatu",
    iso3Code: "VUT",
  ),
  Country(
    isoCode: "VE",
    currencyCode: "VEF",
    currencyName: S.current.VEF_name,
    name: "Venezuela (Bolivarian Republic of)",
    iso3Code: "VEN",
  ),
  Country(
    isoCode: "VN",
    currencyCode: "VND",
    currencyName: S.current.VND_name,
    name: "Viet Nam",
    iso3Code: "VNM",
  ),
  Country(
    isoCode: "WF",
    currencyCode: "XPF",
    currencyName: S.current.XPF_name,
    name: "Wallis and Futuna",
    iso3Code: "WLF",
  ),
  Country(
    isoCode: "EH",
    currencyCode: "MAD",
    currencyName: S.current.MAD_name,
    name: "Western Sahara",
    iso3Code: "ESH",
  ),
  Country(
    isoCode: "YE",
    currencyCode: "YER",
    currencyName: S.current.YER_name,
    name: "Yemen",
    iso3Code: "YEM",
  ),
  Country(
    isoCode: "ZM",
    currencyCode: "ZMW",
    currencyName: S.current.ZMW_name,
    name: "Zambia",
    iso3Code: "ZMB",
  ),
  Country(
    isoCode: "ZW",
    currencyCode: "BWP",
    currencyName: S.current.BWP_name,
    name: "Zimbabwe",
    iso3Code: "ZWE",
  ),
];

